// ── Shared error hierarchy ──────────────────────────────────

export { ZodError } from 'zod';
export type {
	AccessControlConfig,
	AccessControlSensitivityConfig,
	AnalysisConfig,
	ApiAuthConfig,
	ApiAuthKeyConfig,
	ApiBudgetConfig,
	ApiConfig,
	ApiRateLimitingConfig,
	CloudSqlConfig,
	ConfigIssue,
	ContradictionManagementConfig,
	CredibilityConfig,
	CredibilityDimensionConfig,
	DeduplicationConfig,
	DocumentAiConfig,
	DocumentQualityConfig,
	EmbeddingConfig,
	EnrichmentConfig,
	EntityResolutionConfig,
	EntityTypeConfig,
	ExtractionConfig,
	GcpConfig,
	GroundingConfig,
	IngestionConfig,
	IngestProvenanceConfig,
	MulderConfig,
	OntologyConfig,
	PatternDiscoveryConfig,
	PipelineConfig,
	ProjectConfig,
	RelationshipConfig,
	ReprocessHashStepName,
	RetrievalConfig,
	SafetyConfig,
	SourceRollbackConfig,
	StorageConfig,
	TaxonomyConfig,
	ThresholdsConfig,
	VertexConfig,
	VisualIntelligenceConfig,
} from './config/index.js';
// ── Config ──────────────────────────────────────────────────
export {
	CONFIG_DEFAULTS,
	ConfigValidationError,
	computeReprocessConfigHash,
	getReprocessConfigSubset,
	loadConfig,
	mulderConfigSchema,
} from './config/index.js';
export type {
	AcquisitionChannel,
	AcquisitionContext,
	AcquisitionContextInput,
	AcquisitionContextStatus,
	ApplyTaxonomyChangesInput,
	Archive,
	ArchiveCompleteness,
	ArchiveInput,
	ArchiveLocation,
	ArchiveLocationInput,
	ArchiveSourceStatus,
	ArchiveStatus,
	ArchiveType,
	ArtifactProvenance,
	ArtifactProvenanceInput,
	AssertionType,
	AttributeCandidate,
	AuditLogEvent,
	AuthenticityStatus,
	Chunk,
	ChunkFilter,
	ChunkRow,
	ClassificationProvenance,
	ClusterableEntityEvent,
	Collection,
	CollectionDefaults,
	CollectionInput,
	CollectionListOptions,
	CollectionSummary,
	CollectionType,
	CollectionUpdateInput,
	CollectionVisibility,
	CompactDocumentQualitySummary,
	ConfidenceMetadata,
	ConflictAssertion,
	ConflictDetectionMethod,
	ConflictInvolvementBySource,
	ConflictNode,
	ConflictNodeListOptions,
	ConflictParticipantRole,
	ConflictResolution,
	ConflictResolutionStatus,
	ConflictSeverity,
	ConflictType,
	CreateChunkInput,
	CreateConflictAssertionInput,
	CreateConflictNodeInput,
	CreateDocumentQualityAssessmentInput,
	CreateEdgeInput,
	CreateEntityAliasInput,
	CreateEntityInput,
	CreateEvidenceChainInput,
	CreateMonthlyBudgetReservationInput,
	CreatePipelineRunInput,
	CreateSourceInput,
	CreateSpatioTemporalClusterInput,
	CreateStoryInput,
	CreateTaxonomyEntryInput,
	CredibilityDimension,
	CredibilityProfileAuthor,
	CredibilityReviewStatus,
	CredibilitySourceType,
	CustodyAction,
	CustodyHolderType,
	CustodyStep,
	CustodyStepInput,
	DeadLetterRetryFilter,
	DeadLetterRetryResult,
	DequeueJobResult,
	DocumentBlob,
	DocumentBlobIntegrityStatus,
	DocumentBlobStorageClass,
	DocumentBlobStorageStatus,
	DocumentOverallQuality,
	DocumentQualityAssessment,
	DocumentQualityAssessmentMethod,
	DocumentQualityDimensions,
	DocumentQualityOverride,
	DocumentQualitySignals,
	DocumentStructureType,
	EdgeType,
	EdgeTypePageFilter,
	EmbeddingCandidate,
	EnqueueJobInput,
	Entity,
	EntityAlias,
	EntityCorroborationStats,
	EntityEdge,
	EntityFilter,
	EntityGrounding,
	EvidenceChain,
	ExtractionPath,
	FailedSourceInfo,
	FtsSearchResult,
	GraphTraversalResult,
	GroundingCoordinates,
	IngestProvenanceBundle,
	Job,
	JobClaim,
	JobFilter,
	JobPayload,
	JobStatus,
	KnowledgeAssertion,
	LinkStoryEntityInput,
	ListKnowledgeAssertionsInput,
	MergeEntitiesResult,
	MigrationResult,
	MigrationStatus,
	MonthlyBudgetReservation,
	MonthlyBudgetReservationStatus,
	MonthlyBudgetSummary,
	NormalizationResult,
	OriginalSource,
	OriginalSourceInput,
	OriginalSourceType,
	PathSegment,
	PathSegmentType,
	PersistedSource,
	PhysicalLocation,
	PipelineRun,
	PipelineRunSource,
	PipelineRunSourceStatus,
	PipelineRunStatus,
	PipelineStep,
	PurgeSourceInput,
	ReapJobsResult,
	RecordIngestProvenanceInput,
	ResolutionType,
	ResolveCollectionForIngestInput,
	ResolveConflictNodeInput,
	RestoreSourceInput,
	SoftDeleteSourceInput,
	Source,
	SourceCredibilityProfile,
	SourceCredibilityProfileListOptions,
	SourceDeletion,
	SourceDeletionState,
	SourceDeletionStatus,
	SourceFilter,
	SourceFormatMetadata,
	SourcePurgeEffects,
	SourcePurgePlan,
	SourcePurgeReport,
	SourcePurgeSubsystemCount,
	SourceReliabilityFilter,
	SourceRollbackOrphanHandling,
	SourceStatus,
	SourceStep,
	SourceStepStatus,
	SourceType,
	SourceWithSteps,
	SourceWithStepsFilter,
	SpatialEntityEventPair,
	SpatioTemporalCluster,
	SpatioTemporalClusterFilter,
	SpatioTemporalClusterType,
	Story,
	StoryEntity,
	StoryFilter,
	StoryStatus,
	SubmittedBy,
	SubmittedByType,
	TaxonomyEntry,
	TaxonomyEntryStatus,
	TaxonomyFilter,
	TaxonomySimilarityMatch,
	UpdateEntityInput,
	UpdateSourceInput,
	UpdateStoryInput,
	UpdateTaxonomyEntryInput,
	UpsertCredibilityDimensionInput,
	UpsertDocumentBlobInput,
	UpsertEntityGroundingInput,
	UpsertKnowledgeAssertionInput,
	UpsertPipelineRunSourceInput,
	UpsertSourceCredibilityProfileInput,
	UpsertSourceStepInput,
	UrlHostLifecycle,
	UrlLifecycle,
	UrlLifecycleChangeKind,
	VectorSearchResult,
} from './database/index.js';
// ── Database ─────────────────────────────────────────────────
export {
	addCollectionTags,
	applyGroundingToEntity,
	applyTaxonomyChanges,
	closeAllPools,
	countChunks,
	countEdges,
	countEdgesByTypes,
	countEntities,
	countEntitiesByType,
	countEvidenceChains,
	countEvidenceChainsByThesis,
	countEvidenceTheses,
	countJobs,
	countPipelineRunSourcesByStatus,
	countProcessedSources,
	countScoredSources,
	countSources,
	countSourcesByStatus,
	countSpatioTemporalClusters,
	countStories,
	countStoriesByStatus,
	countTaxonomyEntries,
	createArchive,
	createChunk,
	createChunks,
	createCollection,
	createConflictNode,
	createDocumentQualityAssessment,
	createEdge,
	createEntity,
	createEntityAlias,
	createEvidenceChains,
	createMonthlyBudgetReservation,
	createPipelineRun,
	createSource,
	createSpatioTemporalClusters,
	createStory,
	createTaxonomyEntry,
	deleteAliasesByEntityId,
	deleteAllSpatioTemporalClusters,
	deleteAutoTaxonomyEntries,
	deleteChunksBySourceId,
	deleteChunksByStoryId,
	deleteConflictNodesForStory,
	deleteEdgesBySourceId,
	deleteEdgesByStoryId,
	deleteEntitiesBySourceId,
	deleteEntityAlias,
	deleteEvidenceChainsByThesis,
	deleteGraphDerivedEdgesBySourceId,
	deleteKnowledgeAssertionsForStory,
	deleteSource,
	deleteSourceStep,
	deleteStoriesBySourceId,
	deleteStory,
	deleteStoryEntitiesBySourceId,
	deleteStoryEntitiesByStoryId,
	deleteTaxonomyEntry,
	dequeueJob,
	enqueueJob,
	finalizeMonthlyBudgetReservation,
	finalizePipelineRun,
	findAcquisitionContextById,
	findAliasesByEntityId,
	findAllEdges,
	findAllEdgesByTypes,
	findAllEntities,
	findAllEvidenceChains,
	findAllSources,
	findAllSpatioTemporalClusters,
	findAllStories,
	findAllTaxonomyEntries,
	findAllTaxonomyEntriesUnpaginated,
	findArchiveById,
	findCandidatesByAttributes,
	findCandidatesByEmbedding,
	findChunkById,
	findChunksBySourceId,
	findChunksByStoryId,
	findCollectionById,
	findCollectionByName,
	findConflictNodeById,
	findConflictNodeByLegacyEdgeId,
	findDeadLetterJobs,
	findDocumentBlobByHash,
	findDocumentQualityAssessmentById,
	findEdgeById,
	findEdgesByEntityId,
	findEdgesByStoryId,
	findEdgesByType,
	findEntitiesByCanonicalId,
	findEntitiesByStoryId,
	findEntitiesByType,
	findEntityByAlias,
	findEntityById,
	findEntityGroundingByEntityId,
	findEvidenceChainsByThesis,
	findJobById,
	findJobs,
	findLatestDocumentQualityAssessment,
	findLatestMonthlyBudgetReservationForSource,
	findLatestPipelineRun,
	findLatestPipelineRunSourceForSource,
	findMonthlyBudgetReservationByRunId,
	findOriginalSourceForContext,
	findPipelineRunById,
	findPipelineRunSourceById,
	findPipelineRunSourcesByRunId,
	findScoredSources,
	findSourceByCrossFormatDedupKey,
	findSourceByHash,
	findSourceById,
	findSourceCredibilityProfileBySourceId,
	findSourceDeletionForSource,
	findSourceStep,
	findSourceSteps,
	findSourcesWithFailedSteps,
	findSourcesWithSteps,
	findSpatialEntityEventPairs,
	findStoriesByEntityId,
	findStoriesBySourceId,
	findStoryById,
	findTaxonomyEntryById,
	findTaxonomyEntryByName,
	findUrlHostLifecycleByHost,
	findUrlLifecycleBySourceId,
	gcOrphanedEntities,
	getEntityCorroborationStats,
	getMigrationStatus,
	getQueryPool,
	getWorkerPool,
	linkStoryEntity,
	listAcquisitionContextsForBlob,
	listAcquisitionContextsForSource,
	listArchiveLocationsForBlob,
	listArchives,
	listAuditEventsForSource,
	listCollections,
	listConflictInvolvementBySource,
	listConflictNodes,
	listCustodyChainForContext,
	listDocumentQualityAssessmentsForSource,
	listKnowledgeAssertionsForSource,
	listKnowledgeAssertionsForStory,
	listOpenConflictNodes,
	listSourceCredibilityProfiles,
	listSourceDeletions,
	loadClusterableEntityEvents,
	mapArtifactProvenanceFromDb,
	mapArtifactProvenanceToDb,
	markAcquisitionContextsForSourceDeleted,
	markJobCompleted,
	markJobDeadLetter,
	markJobFailed,
	mergeEntities,
	mergeJobPayload,
	normalizeCollectionTags,
	normalizeConfidenceMetadata,
	normalizeDocumentQualityDimensions,
	normalizeDocumentQualitySignals,
	persistEntityGroundingResult,
	planSourcePurge,
	provenanceForSource,
	purgeSource,
	reapRunningJobs,
	recordAcquisitionContext,
	recordArchiveLocation,
	recordCustodyStep,
	recordIngestProvenance,
	recordOriginalSource,
	recordUrlHostLifecycle,
	recordUrlLifecycleFetch,
	removeCollectionTags,
	replaceCustodyChain,
	replaceSpatioTemporalClustersSnapshot,
	resetDeadLetterJobs,
	resetPipelineStep,
	resolveCollectionForIngest,
	resolveConflictNode,
	restoreAcquisitionContextsForSource,
	restoreSource,
	runMigrations,
	searchByFts,
	searchByVector,
	searchByVectorWithEfSearch,
	searchTaxonomyBySimilarity,
	setCollectionTags,
	softDeleteSource,
	stringifyArtifactProvenance,
	summarizeCollection,
	summarizeMonthlyBudgetReservations,
	traverseGraph,
	unlinkStoryEntity,
	updateChunkEmbedding,
	updateCollection,
	updateEdge,
	updateEntity,
	updateEntityEmbedding,
	updateSource,
	updateSourceSensitivityFromArtifacts,
	updateSourceStatus,
	updateStory,
	updateStorySensitivityFromArtifacts,
	updateStoryStatus,
	updateTaxonomyEntry,
	upsertArchive,
	upsertArchiveMirrorCollection,
	upsertDocumentBlob,
	upsertEdge,
	upsertEntityByNameType,
	upsertEntityGrounding,
	upsertKnowledgeAssertion,
	upsertPipelineRunSource,
	upsertSourceCredibilityProfile,
	upsertSourceStep,
} from './database/index.js';
// ── LLM cache ────────────────────────────────────────────────
export type { CacheEntry, CacheStats, LlmCache } from './llm-cache.js';
export { createLlmCache, DEFAULT_CACHE_DB_PATH } from './llm-cache.js';
export type { NativeTextDetectOptions, NativeTextResult, PdfMetadata } from './pipeline/index.js';
// ── Pipeline utilities ─────────────────────────────────────
export { detectNativeText, extractPdfMetadata } from './pipeline/index.js';
// ── Prompt template engine ─────────────────────────────────
export { clearPromptCaches, listTemplates, renderPrompt } from './prompts/index.js';
export {
	assertSha256ContentHash,
	buildContentAddressedBlobPath,
	buildContentAddressedBlobUri,
} from './shared/blob-storage.js';
export type {
	BudgetablePipelineStep,
	BudgetEstimate,
	BudgetReservationFinalization,
} from './shared/budget.js';
export {
	BUDGETABLE_PIPELINE_STEP_VALUES,
	budgetMonthStart,
	completedStepsFromProgress,
	estimateBudgetForSourceRun,
	finalizeBudgetReservation,
	isBudgetablePipelineStep,
	secondsUntilNextBudgetMonth,
} from './shared/budget.js';
// ── Cache hash ───────────────────────────────────────────────
export type { CacheKeyParams } from './shared/cache-hash.js';
export { computeCacheKey } from './shared/cache-hash.js';
export type { ReprocessableStep } from './shared/config-fingerprint.js';
export {
	getAllStepConfigHashes,
	getForcedReprocessSteps,
	getReprocessPlanForHashes,
	getStepConfigHash,
} from './shared/config-fingerprint.js';
export type {
	CorroborationPresentationContext,
	CorroborationPresentationStatus,
	PresentedCorroborationScore,
} from './shared/corroboration.js';
export { isCorroborationMeaningful, presentCorroborationScore } from './shared/corroboration.js';
export type {
	CostEstimate,
	CostEstimateInput,
	CostEstimateStepLine,
	EstimatedSourceProfile,
	EstimatedStep,
} from './shared/cost-estimator.js';
export { estimatePipelineCost } from './shared/cost-estimator.js';
export { createEmailExtractorService } from './shared/email-extractor.js';
export type {
	AnalyzeErrorCode,
	ConfigErrorCode,
	DatabaseErrorCode,
	EmbedErrorCode,
	EnrichErrorCode,
	ExternalServiceErrorCode,
	ExtractErrorCode,
	GraphErrorCode,
	GroundErrorCode,
	IngestErrorCode,
	MulderErrorCode,
	PipelineErrorCode,
	PromptErrorCode,
	RetrievalErrorCode,
	SegmentErrorCode,
	TaxonomyErrorCode,
} from './shared/errors.js';
export {
	ANALYZE_ERROR_CODES,
	AnalyzeError,
	CONFIG_ERROR_CODES,
	ConfigError,
	DATABASE_ERROR_CODES,
	DatabaseError,
	EMBED_ERROR_CODES,
	EmbedError,
	ENRICH_ERROR_CODES,
	EnrichError,
	EXTERNAL_SERVICE_ERROR_CODES,
	EXTRACT_ERROR_CODES,
	ExternalServiceError,
	ExtractError,
	GRAPH_ERROR_CODES,
	GROUND_ERROR_CODES,
	GraphError,
	GroundError,
	INGEST_ERROR_CODES,
	IngestError,
	isMulderError,
	isRetryableError,
	MulderError,
	PIPELINE_ERROR_CODES,
	PipelineError,
	PROMPT_ERROR_CODES,
	PromptError,
	RETRIEVAL_ERROR_CODES,
	RetrievalError,
	SEGMENT_ERROR_CODES,
	SegmentError,
	TAXONOMY_ERROR_CODES,
	TaxonomyError,
} from './shared/errors.js';
export { closeGcpClients } from './shared/gcp.js';
export type {
	ChildLoggerContext,
	Logger,
	LoggerOptions,
} from './shared/logger.js';
// ── Logger ──────────────────────────────────────────────────
export {
	createChildLogger,
	createLogger,
	withDuration,
} from './shared/logger.js';
export type { PipelinePlanStep, StepPlan, StepPlanInput } from './shared/pipeline-step-plan.js';
export {
	computeRequestedSteps,
	isLayoutSourceType,
	isPrestructuredSourceType,
	LAYOUT_SOURCE_TYPES,
	PIPELINE_STEP_ORDER,
	PRESTRUCTURED_SOURCE_TYPES,
	planPipelineSteps,
} from './shared/pipeline-step-plan.js';
export type { RateLimiterOptions } from './shared/rate-limiter.js';
// ── Rate limiter ────────────────────────────────────────────
export { RateLimiter } from './shared/rate-limiter.js';
// ── Service abstraction ─────────────────────────────────────
export { createServiceRegistry } from './shared/registry.js';
export type { RetryOptions } from './shared/retry.js';
// ── Retry ───────────────────────────────────────────────────
export { withRetry } from './shared/retry.js';
export type {
	PIIType,
	SensitivityAssignmentSource,
	SensitivityLevel,
	SensitivityMetadata,
	SensitivityMetadataInput,
	SensitivityTagged,
} from './shared/sensitivity.js';
export {
	defaultSensitivityMetadata,
	isSensitivityLevel,
	mapSensitivityMetadataToDb,
	mergeSensitivityMetadata,
	mostRestrictiveSensitivityLevel,
	normalizeSensitivityMetadata,
	PII_TYPES,
	SENSITIVITY_ASSIGNMENT_SOURCES,
	SENSITIVITY_LEVELS,
	stringifySensitivityMetadata,
} from './shared/sensitivity.js';
export { createGcpServices } from './shared/services.gcp.js';
export type {
	DocumentAiResult,
	DocumentAiService,
	EmailAddress,
	EmailAttachment,
	EmailAttachmentSummary,
	EmailExtractionResult,
	EmailExtractorService,
	EmailFormat,
	EmailHeaders,
	EmbeddingResult,
	EmbeddingService,
	FirestoreService,
	GroundedGenerateOptions,
	GroundedGenerateResult,
	LlmService,
	OfficeDocumentExtractionMessage,
	OfficeDocumentExtractionResult,
	OfficeDocumentExtractorService,
	ServiceMode,
	Services,
	SpreadsheetExtractionResult,
	SpreadsheetExtractorService,
	SpreadsheetRowGroup,
	SpreadsheetSheet,
	SpreadsheetTableSummary,
	SpreadsheetTabularFormat,
	StorageListResult,
	StorageService,
	StructuredGenerateOptions,
	TextGenerateOptions,
	UrlEntityHint,
	UrlExtractionResult,
	UrlExtractorService,
	UrlFetcherService,
	UrlFetchOptions,
	UrlFetchResult,
	UrlRendererService,
	UrlRenderOptions,
	UrlRenderResult,
} from './shared/services.js';
export type { StepError } from './shared/types.js';
export { createUrlExtractorService } from './shared/url-extractor.js';
export { createUrlFetcherService } from './shared/url-fetcher.js';
export {
	computeUrlLifecycleNextAllowedAt,
	headerValue as urlLifecycleHeaderValue,
	normalizeUrlLifecycleHost,
	resolveUrlPolitenessDelayMs,
	sleepForUrlPoliteness,
} from './shared/url-lifecycle.js';
export { createUrlRendererService } from './shared/url-renderer.js';
// ── Vertex AI wrapper ────────────────────────────────────────
export type { VertexClient, VertexClientOptions } from './vertex.js';
export { createVertexClient } from './vertex.js';
