// ── Shared error hierarchy ──────────────────────────────────

export type {
	AnalysisConfig,
	CloudSqlConfig,
	ConfigIssue,
	DeduplicationConfig,
	DocumentAiConfig,
	EmbeddingConfig,
	EnrichmentConfig,
	EntityResolutionConfig,
	EntityTypeConfig,
	ExtractionConfig,
	GcpConfig,
	GroundingConfig,
	IngestionConfig,
	MulderConfig,
	OntologyConfig,
	PatternDiscoveryConfig,
	PipelineConfig,
	ProjectConfig,
	RelationshipConfig,
	RetrievalConfig,
	SafetyConfig,
	StorageConfig,
	TaxonomyConfig,
	ThresholdsConfig,
	VertexConfig,
	VisualIntelligenceConfig,
} from './config/index.js';
// ── Config ──────────────────────────────────────────────────
export {
	CONFIG_DEFAULTS,
	ConfigValidationError,
	loadConfig,
	mulderConfigSchema,
} from './config/index.js';
export type {
	ApplyTaxonomyChangesInput,
	AttributeCandidate,
	Chunk,
	ChunkFilter,
	ChunkRow,
	CreateChunkInput,
	CreateEdgeInput,
	CreateEntityAliasInput,
	CreateEntityInput,
	CreatePipelineRunInput,
	CreateSourceInput,
	CreateStoryInput,
	CreateTaxonomyEntryInput,
	EdgeType,
	EmbeddingCandidate,
	Entity,
	EntityAlias,
	EntityEdge,
	EntityFilter,
	EntityGrounding,
	FailedSourceInfo,
	FtsSearchResult,
	GraphTraversalResult,
	GroundingCoordinates,
	LinkStoryEntityInput,
	MergeEntitiesResult,
	MigrationResult,
	MigrationStatus,
	NormalizationResult,
	PipelineRun,
	PipelineRunSource,
	PipelineRunSourceStatus,
	PipelineRunStatus,
	PipelineStep,
	Source,
	SourceFilter,
	SourceStatus,
	SourceStep,
	SourceStepStatus,
	Story,
	StoryEntity,
	StoryFilter,
	StoryStatus,
	TaxonomyEntry,
	TaxonomyEntryStatus,
	TaxonomyFilter,
	TaxonomySimilarityMatch,
	UpdateEntityInput,
	UpdateSourceInput,
	UpdateStoryInput,
	UpdateTaxonomyEntryInput,
	UpsertEntityGroundingInput,
	UpsertPipelineRunSourceInput,
	UpsertSourceStepInput,
	VectorSearchResult,
} from './database/index.js';
// ── Database ─────────────────────────────────────────────────
export {
	applyGroundingToEntity,
	applyTaxonomyChanges,
	closeAllPools,
	countChunks,
	countEdges,
	countEntities,
	countEntitiesByType,
	countPipelineRunSourcesByStatus,
	countProcessedSources,
	countSources,
	countSourcesByStatus,
	countStories,
	countStoriesByStatus,
	countTaxonomyEntries,
	createChunk,
	createChunks,
	createEdge,
	createEntity,
	createEntityAlias,
	createPipelineRun,
	createSource,
	createStory,
	createTaxonomyEntry,
	deleteAliasesByEntityId,
	deleteAutoTaxonomyEntries,
	deleteChunksBySourceId,
	deleteChunksByStoryId,
	deleteEdgesBySourceId,
	deleteEdgesByStoryId,
	deleteEntitiesBySourceId,
	deleteEntityAlias,
	deleteSource,
	deleteSourceStep,
	deleteStoriesBySourceId,
	deleteStory,
	deleteStoryEntitiesBySourceId,
	deleteStoryEntitiesByStoryId,
	deleteTaxonomyEntry,
	finalizePipelineRun,
	findAliasesByEntityId,
	findAllEdges,
	findAllEntities,
	findAllSources,
	findAllStories,
	findAllTaxonomyEntries,
	findAllTaxonomyEntriesUnpaginated,
	findCandidatesByAttributes,
	findCandidatesByEmbedding,
	findChunkById,
	findChunksBySourceId,
	findChunksByStoryId,
	findEdgesByEntityId,
	findEdgesByStoryId,
	findEdgesByType,
	findEntitiesByCanonicalId,
	findEntitiesByStoryId,
	findEntitiesByType,
	findEntityByAlias,
	findEntityById,
	findEntityGroundingByEntityId,
	findLatestPipelineRun,
	findLatestPipelineRunSourceForSource,
	findPipelineRunById,
	findPipelineRunSourceById,
	findPipelineRunSourcesByRunId,
	findSourceByHash,
	findSourceById,
	findSourceStep,
	findSourceSteps,
	findSourcesWithFailedSteps,
	findStoriesByEntityId,
	findStoriesBySourceId,
	findStoryById,
	findTaxonomyEntryById,
	findTaxonomyEntryByName,
	gcOrphanedEntities,
	getMigrationStatus,
	getQueryPool,
	getWorkerPool,
	linkStoryEntity,
	mergeEntities,
	persistEntityGroundingResult,
	resetPipelineStep,
	runMigrations,
	searchByFts,
	searchByVector,
	searchByVectorWithEfSearch,
	searchTaxonomyBySimilarity,
	traverseGraph,
	unlinkStoryEntity,
	updateChunkEmbedding,
	updateEdge,
	updateEntity,
	updateEntityEmbedding,
	updateSource,
	updateSourceStatus,
	updateStory,
	updateStoryStatus,
	updateTaxonomyEntry,
	upsertEdge,
	upsertEntityByNameType,
	upsertEntityGrounding,
	upsertPipelineRunSource,
	upsertSourceStep,
} from './database/index.js';
// ── LLM cache ────────────────────────────────────────────────
export type { CacheEntry, CacheStats, LlmCache } from './llm-cache.js';
export { createLlmCache, DEFAULT_CACHE_DB_PATH } from './llm-cache.js';
export type { NativeTextDetectOptions, NativeTextResult, PdfMetadata } from './pipeline/index.js';
// ── Pipeline utilities ─────────────────────────────────────
export { detectNativeText, extractPdfMetadata } from './pipeline/index.js';
// ── Prompt template engine ─────────────────────────────────
export { clearPromptCaches, listTemplates, renderPrompt } from './prompts/index.js';
// ── Cache hash ───────────────────────────────────────────────
export type { CacheKeyParams } from './shared/cache-hash.js';
export { computeCacheKey } from './shared/cache-hash.js';
export type {
	AnalyzeErrorCode,
	ConfigErrorCode,
	DatabaseErrorCode,
	EmbedErrorCode,
	EnrichErrorCode,
	ExternalServiceErrorCode,
	ExtractErrorCode,
	GraphErrorCode,
	GroundErrorCode,
	IngestErrorCode,
	MulderErrorCode,
	PipelineErrorCode,
	PromptErrorCode,
	RetrievalErrorCode,
	SegmentErrorCode,
	TaxonomyErrorCode,
} from './shared/errors.js';
export {
	ANALYZE_ERROR_CODES,
	AnalyzeError,
	CONFIG_ERROR_CODES,
	ConfigError,
	DATABASE_ERROR_CODES,
	DatabaseError,
	EMBED_ERROR_CODES,
	EmbedError,
	ENRICH_ERROR_CODES,
	EnrichError,
	EXTERNAL_SERVICE_ERROR_CODES,
	EXTRACT_ERROR_CODES,
	ExternalServiceError,
	ExtractError,
	GRAPH_ERROR_CODES,
	GROUND_ERROR_CODES,
	GraphError,
	GroundError,
	INGEST_ERROR_CODES,
	IngestError,
	isMulderError,
	isRetryableError,
	MulderError,
	PIPELINE_ERROR_CODES,
	PipelineError,
	PROMPT_ERROR_CODES,
	PromptError,
	RETRIEVAL_ERROR_CODES,
	RetrievalError,
	SEGMENT_ERROR_CODES,
	SegmentError,
	TAXONOMY_ERROR_CODES,
	TaxonomyError,
} from './shared/errors.js';
export { closeGcpClients } from './shared/gcp.js';
export type {
	ChildLoggerContext,
	Logger,
	LoggerOptions,
} from './shared/logger.js';
// ── Logger ──────────────────────────────────────────────────
export {
	createChildLogger,
	createLogger,
	withDuration,
} from './shared/logger.js';
export type { RateLimiterOptions } from './shared/rate-limiter.js';
// ── Rate limiter ────────────────────────────────────────────
export { RateLimiter } from './shared/rate-limiter.js';
// ── Service abstraction ─────────────────────────────────────
export { createServiceRegistry } from './shared/registry.js';
export type { RetryOptions } from './shared/retry.js';
// ── Retry ───────────────────────────────────────────────────
export { withRetry } from './shared/retry.js';
export { createGcpServices } from './shared/services.gcp.js';
export type {
	DocumentAiResult,
	DocumentAiService,
	EmbeddingResult,
	EmbeddingService,
	FirestoreService,
	GroundedGenerateOptions,
	GroundedGenerateResult,
	LlmService,
	ServiceMode,
	Services,
	StorageListResult,
	StorageService,
	StructuredGenerateOptions,
	TextGenerateOptions,
} from './shared/services.js';
export type { StepError } from './shared/types.js';
// ── Vertex AI wrapper ────────────────────────────────────────
export type { VertexClient, VertexClientOptions } from './vertex.js';
export { createVertexClient } from './vertex.js';
