export const copy = {
  nav: {
    desk: 'The Desk',
    archive: 'Archive',
    board: 'Board',
    ask: 'Ask',
  },
  archive: {
    title: 'Open the archive.',
    body: 'Browse the document set, filter the shelves, and drop in new PDFs when the route is available.',
    table: {
      thumbnail: 'Thumbnail',
      document: 'Document',
      pages: 'Pages',
      entities: 'Entities',
      status: 'Status',
      added: 'Added',
      loadMore: 'Load more documents',
      emptyLoad: 'No more documents match the current filters.',
    },
    filters: {
      title: 'Filters',
      status: 'Status',
      dateAdded: 'Date added',
      language: 'Language',
      sourceType: 'Source type',
      all: 'All',
      pdfOnly: 'PDF only',
    },
    sort: {
      label: 'Sort by',
      recent: 'Recent',
      alphabetical: 'Alphabetical',
      size: 'Size',
      density: 'Entity density',
    },
    empty: {
      title: 'The archive is empty.',
      body: 'Drop a PDF anywhere on this screen to begin.',
      action: 'Choose a PDF',
    },
    upload: {
      title: 'Upload document',
      body: 'Send a PDF to the archive and let the pipeline queue the rest.',
      label: 'Archive upload',
      cue: 'Drop anywhere to upload',
      unsupported: 'Uploading is a CLI operation today (`mulder ingest <path>`).',
      preparing: 'Preparing upload',
      uploading: 'Uploading PDF',
      queued: 'Queued for extraction',
      parsing: 'Parsing PDF',
      extracted: 'Extracted',
      failed: 'Upload failed',
      workerFailed: 'The archive worker failed before it could finish.',
      chooseAnother: 'Choose another PDF',
      close: 'Close',
      drop: 'Drop to upload',
      selectPdf: 'Choose a PDF file.',
      bytesLimit: (maxBytes: number) => `Maximum upload size: ${(maxBytes / (1024 * 1024)).toFixed(0)} MB`,
    },
    row: {
      layoutReady: 'Layout ready',
      awaitingExtraction: 'Awaiting story extraction',
      moreAvailable: 'More documents are available.',
      preview: 'Preview',
    },
    controls: {
      collapseFilters: 'Collapse filters',
      expandFilters: 'Expand filters',
    },
  },
  desk: {
    title: 'The Desk',
    body: 'What matters now: the archive totals, the newest additions, and the leads worth following.',
    ribbon: {
      documents: 'Documents in archive',
      entities: 'Entities indexed',
      contradictions: 'Contradictions needing review',
      coverage: 'Archive coverage',
    },
    recent: {
      title: 'Recently added',
      empty: 'No recent documents yet.',
      pages: (count: number | null) => (count === null ? '— pages' : `${count} pages`),
    },
    leads: {
      title: 'Worth following',
      empty: 'The archive needs more documents before leads emerge.',
      contradiction: 'Contradiction confirmed',
      entity: 'New entity',
      corroboration: 'Corroboration',
      openAudit: 'Open audit',
      contradictionDetail: (attribute: string, valueA: string, valueB: string) => `${attribute}: ${valueA} / ${valueB}`,
      entityDetail: (name: string, count: string | number) => `${name} appears in ${count} documents`,
    },
    ribbonNote: 'The desk pulls live numbers from the archive, not fixtures.',
  },
  ask: {
    title: 'Ask the archive.',
    body: 'Run a real hybrid search, inspect the retrieval trace, and jump straight into the cited case file.',
    placeholderExamples: [
      'Who appears in multiple sightings between 1997 and 2001?',
      'What contradictions exist about CUFOS history?',
      'Show documents related to the Phoenix Lights.',
    ],
    form: {
      label: 'Search the archive',
      submit: 'Search',
      rerankOn: 'Gemini reranking on',
      rerankOff: 'Gemini reranking off',
      inputHint: 'Press / to focus search. Press ⌘K for the command palette.',
    },
    answer: {
      title: 'Answer',
      emptyTitle: 'Start with a question.',
      emptyBody: 'The Ask console turns live retrieval results into a tight reading stack with citations and provenance.',
      noResultsTitle: 'No direct matches yet.',
      noResultsBody: 'Try a narrower time range, a named entity, or a document title already in the archive.',
      citations: 'Citations',
      trace: 'How I found this.',
      openCaseFile: 'Open case file',
      confidence: 'Confidence',
      strategy: 'Strategy',
      answerLabel: 'Top passage',
    },
    trace: {
      strategies: 'Strategy breakdown',
      seedEntities: 'Seed entities',
      rerank: 'Rerank status',
      rerankApplied: 'Gemini reranking applied',
      rerankSkipped: 'Gemini reranking skipped',
      none: 'None',
    },
  },
  commandPalette: {
    placeholder: 'Search documents, entities, and actions',
    groups: {
      documents: 'Documents',
      entities: 'Entities',
      goTo: 'Go to',
      actions: 'Actions',
    },
    empty: 'No matching command, document, or entity.',
  },
  shortcuts: {
    title: 'Keyboard shortcuts',
    body: 'Move fast without leaving the page.',
    close: 'Close',
  },
  auth: {
    loginTitle: 'Enter the archive',
    loginBody: 'Use the invitation-backed session for this browser.',
    inviteTitle: 'You have been invited to the Mulder archive.',
    loginFailure: "Those credentials didn't match.",
    sessionExpired: 'Your session has ended. Please log in again.',
    forgotPassword: 'Forgot your password? Ask your operator for a fresh invitation.',
  },
  empty: {
    archive: {
      title: 'The archive is empty.',
      body: 'Drop a PDF anywhere on this screen to begin.',
    },
    story: {
      title: 'No story is selected.',
      body: 'Pick a story to inspect the extracted text and entities.',
    },
  },
  loading: {
    document: (page: number, total: number) => `Reading page ${page} of ${total}`,
  },
  errors: {
    generic: 'Something went wrong while reading the archive.',
    documentNotFound: 'This document could not be found.',
    layoutUnavailable: "This document has been ingested but stories haven't been extracted yet.",
    pdfRead: "Couldn't read this PDF. The scan may be corrupted.",
  },
};
