import type { ActivityEvent, AnalysisRun, EvidenceClaim, Finding, Metric } from '@/lib/types';

export const metrics: Metric[] = [
  { label: 'Documents indexed', value: '847', delta: '+28 this week', tone: 'neutral' },
  { label: 'Entities resolved', value: '12,483', delta: '+9.4%', tone: 'good' },
  { label: 'Open contradictions', value: '18', delta: '6 critical', tone: 'danger' },
  { label: 'Avg. citation depth', value: '4.7', delta: '+0.6', tone: 'good' },
];

export const trend = [18, 24, 21, 32, 37, 42, 38, 51, 58, 63, 71, 68];

export const activity: ActivityEvent[] = [
  {
    id: 'evt-1031',
    label: 'Cluster refresh completed',
    detail: 'Phoenix sightings corpus rebuilt with 128 new edges',
    time: '2m ago',
    status: 'completed',
  },
  {
    id: 'evt-1030',
    label: 'Extraction run started',
    detail: 'Batch docai-2026-04-29-07 is reading page regions',
    time: '8m ago',
    status: 'running',
  },
  {
    id: 'evt-1029',
    label: 'Contradiction watch updated',
    detail: 'Allan Hendry date conflict received a second source',
    time: '24m ago',
    status: 'watching',
  },
  {
    id: 'evt-1028',
    label: 'Grounding failed',
    detail: 'Three low-quality scans skipped for missing page text',
    time: '1h ago',
    status: 'failed',
  },
];

export const runs: AnalysisRun[] = [
  {
    id: 'run_8f42a1',
    title: 'Phoenix cluster corroboration',
    mode: 'graph + retrieval',
    status: 'running',
    owner: 'ops@mulder.ai',
    corpus: 'Sightings archive',
    startedAt: 'Apr 29, 20:06',
    duration: '12m 44s',
    credits: 184,
    progress: 68,
    confidence: 0.86,
    findings: 14,
    query: 'Identify multi-source sightings around Phoenix from 1997-2001.',
    params: {
      rerank: true,
      graphDepth: 2,
      minSourceReliability: 0.62,
      includeContradictions: true,
    },
    artifacts: [
      { name: 'cluster-map.json', type: 'JSON', size: '82 KB' },
      { name: 'evidence-pack.md', type: 'Markdown', size: '41 KB' },
    ],
    timeline: [
      { time: '20:06', label: 'Run accepted', detail: 'Queue slot assigned', status: 'completed' },
      { time: '20:07', label: 'Retrieval pass', detail: '312 candidate chunks', status: 'completed' },
      { time: '20:11', label: 'Graph expansion', detail: '84 related entities', status: 'running' },
      { time: '20:18', label: 'Evidence synthesis', detail: 'Waiting on rerank batch', status: 'queued' },
    ],
  },
  {
    id: 'run_a91d03',
    title: 'CUFOS personnel timeline',
    mode: 'temporal audit',
    status: 'completed',
    owner: 'research@mulder.ai',
    corpus: 'Institution records',
    startedAt: 'Apr 29, 18:42',
    duration: '7m 09s',
    credits: 96,
    progress: 100,
    confidence: 0.91,
    findings: 8,
    query: 'Build a dated timeline for named CUFOS personnel.',
    params: {
      rerank: true,
      graphDepth: 1,
      minSourceReliability: 0.7,
      includeContradictions: true,
    },
    artifacts: [
      { name: 'timeline.csv', type: 'CSV', size: '18 KB' },
      { name: 'claim-diff.json', type: 'JSON', size: '29 KB' },
    ],
    timeline: [
      { time: '18:42', label: 'Run accepted', detail: 'Queue slot assigned', status: 'completed' },
      { time: '18:44', label: 'Claims extracted', detail: '49 dated claims', status: 'completed' },
      { time: '18:47', label: 'Contradictions ranked', detail: '4 review candidates', status: 'completed' },
    ],
  },
  {
    id: 'run_c77120',
    title: 'Rendlesham source quality sweep',
    mode: 'reliability audit',
    status: 'watching',
    owner: 'analyst@mulder.ai',
    corpus: 'UK case files',
    startedAt: 'Apr 29, 17:15',
    duration: '3m 22s',
    credits: 44,
    progress: 100,
    confidence: 0.74,
    findings: 3,
    query: 'Find weakly sourced claims in the Rendlesham collection.',
    params: {
      rerank: false,
      graphDepth: 1,
      minSourceReliability: 0.5,
      includeContradictions: false,
    },
    artifacts: [{ name: 'watchlist.json', type: 'JSON', size: '11 KB' }],
    timeline: [
      { time: '17:15', label: 'Run accepted', detail: 'Queue slot assigned', status: 'completed' },
      { time: '17:16', label: 'Reliability pass', detail: '22 sources scored', status: 'completed' },
      { time: '17:18', label: 'Watchlist created', detail: 'Monitoring 3 claims', status: 'watching' },
    ],
  },
  {
    id: 'run_b2fe19',
    title: 'Scanned bulletin extraction',
    mode: 'layout extraction',
    status: 'failed',
    owner: 'ops@mulder.ai',
    corpus: 'Bulletin imports',
    startedAt: 'Apr 29, 15:03',
    duration: '1m 56s',
    credits: 22,
    progress: 42,
    confidence: 0.41,
    findings: 0,
    query: 'Extract article regions from imported newsletters.',
    params: {
      rerank: false,
      graphDepth: 0,
      minSourceReliability: 0.4,
      includeContradictions: false,
    },
    artifacts: [{ name: 'failed-pages.log', type: 'Log', size: '7 KB' }],
    timeline: [
      { time: '15:03', label: 'Run accepted', detail: 'Queue slot assigned', status: 'completed' },
      { time: '15:04', label: 'Page analysis', detail: 'Low contrast detected', status: 'running' },
      { time: '15:05', label: 'Extraction stopped', detail: 'OCR quality below threshold', status: 'failed' },
    ],
    error: 'OCR confidence dropped below the configured 0.52 threshold on 9 consecutive pages.',
  },
];

export const findings: Finding[] = [
  {
    id: 'fnd-4208',
    title: 'Date conflict around CUFOS assignment',
    summary: 'Two primary-adjacent sources disagree by 24 months.',
    severity: 'critical',
    entity: 'Allan Hendry',
    createdAt: '20:18',
  },
  {
    id: 'fnd-4207',
    title: 'Recurring Phoenix observer group',
    summary: 'Six reports share three named witnesses and overlapping coordinates.',
    severity: 'high',
    entity: 'Phoenix cluster',
    createdAt: '20:12',
  },
  {
    id: 'fnd-4206',
    title: 'Alias resolution improved',
    summary: 'Jennie Zeidman now links across English and Spanish filings.',
    severity: 'medium',
    entity: 'Jennie Zeidman',
    createdAt: '19:54',
  },
];

export const evidenceClaims: EvidenceClaim[] = [
  {
    id: 'clm-1008',
    claim: 'Allan Hendry was stationed at CUFOS in 1978.',
    entity: 'Allan Hendry',
    status: 'contradicted',
    confidence: 0.79,
    lastSeen: 'Apr 29, 18:47',
    sourceCount: 4,
    signals: ['Temporal conflict', 'Primary source favored', 'Needs review'],
    citations: [
      {
        id: 'src-44',
        title: 'CUFOS internal bulletin, vol. 3',
        type: 'Bulletin',
        reliability: 0.86,
        date: '1978',
        locator: 'p. 14',
      },
      {
        id: 'src-91',
        title: 'Retrospective interview transcript',
        type: 'Transcript',
        reliability: 0.58,
        date: '1994',
        locator: 'pp. 7-8',
      },
    ],
  },
  {
    id: 'clm-1007',
    claim: 'A cluster of six sightings occurred within 80km of Phoenix in March 1997.',
    entity: 'Phoenix cluster',
    status: 'corroborated',
    confidence: 0.93,
    lastSeen: 'Apr 29, 20:11',
    sourceCount: 9,
    signals: ['Geo-temporal match', 'Multiple independent witnesses', 'High reliability'],
    citations: [
      {
        id: 'src-22',
        title: 'Arizona field report packet',
        type: 'Field report',
        reliability: 0.91,
        date: '1997',
        locator: 'pp. 3-12',
      },
      {
        id: 'src-27',
        title: 'Local press clipping archive',
        type: 'Press',
        reliability: 0.73,
        date: '1997',
        locator: 'p. 2',
      },
    ],
  },
  {
    id: 'clm-1006',
    claim: 'Rendlesham witness statements share an unverified equipment failure detail.',
    entity: 'Rendlesham Forest',
    status: 'watching',
    confidence: 0.68,
    lastSeen: 'Apr 29, 17:18',
    sourceCount: 3,
    signals: ['Weak source diversity', 'Repeated phrase', 'Watchlist'],
    citations: [
      {
        id: 'src-62',
        title: 'Witness statement digest',
        type: 'Digest',
        reliability: 0.64,
        date: '1981',
        locator: 'p. 6',
      },
      {
        id: 'src-71',
        title: 'Equipment log excerpt',
        type: 'Log',
        reliability: 0.57,
        date: '1980',
        locator: 'row 18',
      },
    ],
  },
  {
    id: 'clm-1005',
    claim: 'Jennie Zeidman appears under three aliases across multilingual files.',
    entity: 'Jennie Zeidman',
    status: 'unverified',
    confidence: 0.61,
    lastSeen: 'Apr 29, 19:54',
    sourceCount: 3,
    signals: ['Alias candidate', 'Cross-lingual match', 'Low citation depth'],
    citations: [
      {
        id: 'src-18',
        title: 'Spanish language case digest',
        type: 'Digest',
        reliability: 0.69,
        date: '2003',
        locator: 'p. 31',
      },
      {
        id: 'src-19',
        title: 'Researcher notes export',
        type: 'Notes',
        reliability: 0.48,
        date: '2004',
        locator: 'line 812',
      },
    ],
  },
];
